[package]
name = "nc_prometheus_exporter"
version = "0.1.0"
authors = ["jo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
serde_json = "*"
confy = "*"
reqwest = { version = "*", features = ["blocking"] }
quick-xml = "*"
rocket = "*"
md5 = "*"
hex = "*"
log = "*"
fern = "*"
chrono = "*"